remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme



title: "Mohammad Fathi"

theme: jekyll-theme-minimal
description: >
  Masterâ€™s graduate in Data Mining (Kharazmi University)  
  Research: AI, Data Mining, Computational Neuroscience, and Neuroimaging Analysis 
  <br><br>
  <a href="https://phat-hee.github.io/Mohammad_Fathi_CV_oct.pdf" target="_blank">ğŸ“„ CV</a><br>
  <a href="mailto:mohammad.s.fathi98@gmail.com">âœ‰ï¸ mohammad.s.fathi98@gmail.com</a><br>
  <a href="https://github.com/phat-hee">ğŸ™ GitHub</a><br>
  <a href="https://linkedin.com/in/mohammad-fathi98">ğŸ”— LinkedIn</a>

show_downloads: false
google_analytics:
